### ISSUE TITLE
exlcude is ignored on 0.11

### ISSUE THREAD

**Issue by blizzz** [ChristophWurst/krankerl#744]
When running `krankerl packaging` it the final archive will contain all files and folders listed in `exclude`. 0.10.1 behaves correctly.

**Comment by ChristophWurst** [comment]
Yes, noticed as well, and I couldn't figure out why, thus removed this feature as we have `.nextcloudignore` support anyway: https://github.com/ChristophWurst/krankerl/pull/742

I'll release v0.12 soon

**Comment by blizzz** [comment]
> .nextcloudignore support anyway

how does this work?

**Comment by ChristophWurst** [comment]
Just like a `.gitignore`. Place it in your app's root or to any sub directory.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/ChristophWurst/krankerl/pull/742
