### ISSUE TITLE
Publish fails with "Could not sign package"

### ISSUE THREAD

**Issue by ilovemilk** [ChristophWurst/krankerl#820]
Hi Christoph,

Thanks for the helpful tool. It's great to have the possibility to automate the publish process.

I try to publish my app to the Nextcloud Appstore but it fails with:

`Could not sign package: error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: ANY PRIVATE KEY`

but the signing is successful with the same private key:

```bash
$ ./occ integrity:sign-app --privateKey="$HOME/.nextcloud/certificates/ransomware_detection.key" --certificate="$HOME/.nextcloud/certificates/ransomware_detection.crt" --path="$(pwd)/apps/$APP_NAME"
Successfully signed "/home/travis/build/undo-ransomware/server/apps/ransomware_detection"
The command "./occ integrity:sign-app --privateKey="$HOME/.nextcloud/certificates/ransomware_detection.key" --certificate="$HOME/.nextcloud/certificates/ransomware_detection.crt" --path="$(pwd)/apps/$APP_NAME"" exited with 0.
```

The Travis output is here: https://travis-ci.com/github/undo-ransomware/ransomware_detection/jobs/452784011
My Travis file is here: https://github.com/undo-ransomware/ransomware_detection/blob/master/.travis.yml

Can you explain me what the problem could be? I'm a bit stuck :)

**Comment by ChristophWurst** [comment]
Hmm. The signing process should be that same as manually doing it with openssl. Maybe it's the openssl lib that we ship?

What system is this? What is your system's openssl version?

**Comment by ilovemilk** [comment]
I only tried in my Travis CI pipeline.
These are the versions:

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

```
openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by ChristophWurst** [comment]
Could it be the format of your private key? https://stackoverflow.com/questions/31630544/cant-get-private-key-with-openssl-no-start-linepem-lib-c703expecting-any-p/50807788

**Comment by ChristophWurst** [comment]
Maybe the signing within Nextcloud is more flexible but the one from Rust is strict.

**Comment by ilovemilk** [comment]
I have variable set in my pipeline that looks like this:

`$'-----BEGIN PRIVATE KEY-----\nMI...A==\n-----END PRIVATE KEY-----\n`

and I write this to the key file with:

`echo $PRIVATE_KEY > $HOME/.nextcloud/certificates/ransomware_detection.key`

The reason for this is that Travis has a problem with multiline variables.

If I generate the md5sum of the original and the generated key they are the same.

**Comment by ChristophWurst** [comment]
Hm. Unfortunately I'm lacking ideas. 

> pem_lib.c:701:Expecting: ANY PRIVATE KEY

this really sounds like it's about the PEM parsing. But I'm just guessing. Mind checking the internet for any related reports?

**Comment by ilovemilk** [comment]
Thanks. I try to debug a bit more on the weekend. Maybe I find something.

**Comment by ChristophWurst** [comment]
Could you try again later with the v0.13? We now use the rust tls implementation instead of the one of the system, I hope that gives more reliable results.
