### ISSUE TITLE
Regression: can not read RSA private key

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/krankerl#858]
@blizzz and I discovered that the latest version can no longer read some of the private keys. Some debugging shows that the keys that start with ``-----BEGIN PRIVATE KEY-----`` work fine, those with ``-----BEGIN RSA PRIVATE KEY-----`` blow up

```
Error: 
   0: Could not sign package
   1: Failed to sign package
   2: Key could not be parsed
```

@icewind1991 could be related to the changes with opentls, right?

**Comment by juliushaertl** [comment]
PR was merged, time for a new release? :grin:

**Comment by ChristophWurst** [comment]
Yep. I tagged and released https://crates.io/crates/nextcloud_appsignature/0.7.1 but somehow it hasn't shown up here yet.

**Comment by ChristophWurst** [comment]
v0.13.1 released https://aur.archlinux.org/packages/krankerl/
