### ISSUE TITLE
package deletes src directories of vendor packages

### ISSUE THREAD

**Issue by tsdicloud** [ChristophWurst/krankerl#895]
krankerl version: 0.13.1

I have developed a nextcloud app which has dependencies to additional vendor packages.
[I can reproduce the issue also with the official OpenId connect app](https://github.com/nextcloud/user_oidc).

Observation:
Vendor packages that contain a `src` directory get the src subtree deleted in resulting `.tar.gz`

Effect:
The result are classloader errors in log as the php files from the vendor packages are missing.

**Comment by ChristophWurst** [comment]
Do you use a .nextclouignore? If so, does it exclude src?

**Comment by tsdicloud** [comment]
Yes, same as user_oidc. And there, it excludes src, but they are still deleted.
Of course, could be a problem before the screen...

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/user_oidc/blob/3072be4c2670753ba39e156f48374de4b64a2479/.nextcloudignore#L21

it should be `/src` to only catch the root src directory :wink: 

https://github.com/nextcloud/mail/blob/80ba123ec770cd98b92ea2f9b19d15fe60ada179/.nextcloudignore#L32 for comparison :)

**Comment by tsdicloud** [comment]
Thanks, this helps.
Julius already hinted me to .nextcloudignore, but two blinds are still two blinds until a person with healthy eyes comes in...

**Comment by ChristophWurst** [comment]
No worries. I only know because I've made the same mistake myself :wink:
